# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f39417317d8db8c69de6f3a8d894d0bad76d721f99ead579f2c209570817b581d999fc5547e9a2c3a6bc4d5d9658c29201fb1893c1d3975c39b65535b21d695c

test:
  secret_key_base: 186ea2f83d0c9a4c49fadcb1c93b322efc374a0cc2d08d1ff3b1fceea6bfb86c4da1c5c8f5d2bac239d907f6e5ef5f64cbe7cbce079530c19057253bf18dd43a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
